version: "3.9"

networks:
  uniadmit-network:
    driver: bridge

# -------------------------------------------------------
# VOLUMES
# -------------------------------------------------------

volumes:
  auth-data:
  profile-data:
  admission-data:
  document-data:
  payment-data:
  admin-data:

  rabbitmq-data:
  minio-data:
  grafana-data:

# -------------------------------------------------------
# SERVICES
# -------------------------------------------------------

services:

  ##########################################################
  # POSTGRES DATABASES
  ##########################################################

  auth-postgres:
    image: postgres:17
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
    networks:
      - uniadmit-network

  profile-postgres:
    image: postgres:17
    container_name: profile-postgres
    restart: always
    environment:
      POSTGRES_DB: profile_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - profile-data:/var/lib/postgresql/data
    networks:
      - uniadmit-network

  admission-postgres:
    image: postgres:17
    container_name: admission-postgres
    restart: always
    environment:
      POSTGRES_DB: admission_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - admission-data:/var/lib/postgresql/data
    networks:
      - uniadmit-network

  document-postgres:
    image: postgres:17
    container_name: document-postgres
    restart: always
    environment:
      POSTGRES_DB: document_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - document-data:/var/lib/postgresql/data
    networks:
      - uniadmit-network

  payment-postgres:
    image: postgres:17
    container_name: payment-postgres
    restart: always
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - payment-data:/var/lib/postgresql/data
    networks:
      - uniadmit-network

  admin-postgres:
    image: postgres:17
    container_name: admin-postgres
    restart: always
    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - admin-data:/var/lib/postgresql/data
    networks:
      - uniadmit-network

  ##########################################################
  # RABBITMQ
  ##########################################################

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - uniadmit-network

  ##########################################################
  # MINIO
  ##########################################################

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - uniadmit-network

  ##########################################################
  # CONFIG SERVER
  ##########################################################

  config-server:
    build: ./infrastructure/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    restart: always
    networks:
      - uniadmit-network

  ##########################################################
  # EUREKA
  ##########################################################

  eureka-server:
    build: ./infrastructure/eureka-server
    container_name: eureka-server
    depends_on:
      - config-server
    ports:
      - "8761:8761"
    restart: always
    networks:
      - uniadmit-network

  ##########################################################
  # API GATEWAY
  ##########################################################

  api-gateway:
    build: ./infrastructure/api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    restart: always
    networks:
      - uniadmit-network

  ##########################################################
  # AUTH SERVICE
  ##########################################################

  auth-service:
    build: ./services/auth-service
    depends_on:
      - auth-postgres
      - rabbitmq
      - eureka-server
    ports:
      - "8081:8081"
    networks:
      - uniadmit-network

  ##########################################################
  # PROFILE SERVICE
  ##########################################################

  profile-service:
    build: ./services/profile-service
    depends_on:
      - profile-postgres
      - eureka-server
    ports:
      - "8082:8082"
    networks:
      - uniadmit-network

  ##########################################################
  # ADMISSION SERVICE
  ##########################################################

  admission-service:
    build: ./services/admission-service
    depends_on:
      - admission-postgres
      - rabbitmq
      - eureka-server
    ports:
      - "8083:8083"
    networks:
      - uniadmit-network

  ##########################################################
  # DOCUMENT SERVICE
  ##########################################################

  document-service:
    build: ./services/document-service
    depends_on:
      - document-postgres
      - minio
      - eureka-server
    ports:
      - "8084:8084"
    networks:
      - uniadmit-network

  ##########################################################
  # PAYMENT SERVICE
  ##########################################################

  payment-service:
    build: ./services/payment-service
    depends_on:
      - payment-postgres
      - rabbitmq
      - eureka-server
    ports:
      - "8085:8085"
    networks:
      - uniadmit-network

  ##########################################################
  # NOTIFICATION SERVICE
  ##########################################################

  notification-service:
    build: ./services/notification-service
    depends_on:
      - rabbitmq
      - eureka-server
    ports:
      - "8086:8086"
    networks:
      - uniadmit-network

  ##########################################################
  # ADMIN SERVICE
  ##########################################################

  admin-service:
    build: ./services/admin-service
    depends_on:
      - admin-postgres
      - rabbitmq
      - eureka-server
    ports:
      - "8087:8087"
    networks:
      - uniadmit-network

  ##########################################################
  # PROMETHEUS
  ##########################################################

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    networks:
      - uniadmit-network

  ##########################################################
  # GRAFANA
  ##########################################################

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: always
    networks:
      - uniadmit-network