global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    labels:
      service: 'api-gateway'

  # Eureka Server
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8070']
    labels:
      service: 'eureka-server'

  # Auth Service
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
    labels:
      service: 'auth-service'

  # Profile Service
  - job_name: 'profile-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
    labels:
      service: 'profile-service'

  # Admission Service
  - job_name: 'admission-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
    labels:
      service: 'admission-service'

  # Document Service
  - job_name: 'document-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8084']
    labels:
      service: 'document-service'

  # Notification Service
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8086']
    labels:
      service: 'notification-service'

  # Admin Service
  - job_name: 'admin-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8087']
    labels:
      service: 'admin-service'